version: '3.8'

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - app

    app:
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        DB_HOST: db
        DB_PORT: 3306
      volumes:
        - app_logs:/app/logs

    db:
      image: sql:latest
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: test_db
      volumes:
        - db_data:/var/lib/sql
        - db_logs:/var/log/sql

  volumes:
    app_logs:
    db_data:
    db_logs:

